# Generated by Django 5.0.7 on 2024-07-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vid_name", models.CharField(max_length=50)),
                ("vid_file", models.FileField(upload_to="")),
            ],
        ),
    ]
